name: CI/CD

on:
  push:
    branches: [terragrunt]
  pull_request:
    branches: [terragrunt]

env:
  REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  IMAGE: ${{ secrets.CONTAINER_IMAGE }}
  TF_VERSION: 0.13.5
  TG_SRC_PATH: terragrunt

jobs:
  main:
    name: main
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE }}
          BRANCH=${GITHUB_REF#refs/heads/}
          VERSION=${BRANCH}-${GITHUB_RUN_ID}
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            PR_NUMBER=$(echo ${GITHUB_REF} | sed -e 's#refs/pull/\([0-9]\+\)/.*$#\1#g')
            VERSION=PR-${PR_NUMBER}-${GITHUB_RUN_ID}
            BASE_REF=${{ github.event.pull_request.base.ref }}
            BRANCH=${BASE_REF#refs/heads/}
          fi
          TF_WORKSPACE=$([ "$BRANCH" = "main" ] && echo prod || echo ${BRANCH})
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            TF_WORKSPACE=prod
          fi
          TAG="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=tf_workspace::${TF_WORKSPACE}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .
          file: ./Dockerfile
          target: test

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .
          file: ./Dockerfile
          target: runtime
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tag }}

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: 0.26.7

      - name: Terraform Credentials
        run: |
          cat <<EOF >> ~/.terraformrc
          credentials "app.terraform.io" {
            token = "${{ secrets.TFC_TEAM_TOKEN }}"
          }
          EOF

      - name: Terragrunt Validate
        id: tg_validate
        working-directory: ${{ env.TG_SRC_PATH }}/${{ steps.prep.outputs.tf_workspace }}
        env:
          client_app_image_${{ steps.prep.outputs.tf_workspace }}: ${{ steps.prep.outputs.tag }}
        run: terragrunt validate-all

      - name: Terragrunt Plan
        id: tg_plan
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.TG_SRC_PATH }}/${{ steps.prep.outputs.tf_workspace }}
        env:
          client_app_image_${{ steps.prep.outputs.tf_workspace }}: ${{ steps.prep.outputs.tag }}
        run: terragrunt plan-all
